<a href="https://colab.research.google.com/github/siddharthaborgohain/numpy/blob/main/numpy.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import numpy as np

In [2]:
a=np.array([1,2,4,3,5,6])
b=np.array([3,4,7,5,2,9])
a+b

array([ 4,  6, 11,  8,  7, 15])

In [8]:
x=[1,2,4,3,5,6]
y=[3,4,7,5,2,9]
z=x+y
z=np.array(z)
z

array([1, 2, 4, 3, 5, 6, 3, 4, 7, 5, 2, 9])

In [11]:
z.reshape(4,3)

array([[1, 2, 4],
       [3, 5, 6],
       [3, 4, 7],
       [5, 2, 9]])

In [12]:
z.reshape(3,4)

array([[1, 2, 4, 3],
       [5, 6, 3, 4],
       [7, 5, 2, 9]])

In [16]:
p=z.reshape(2,6)
p

array([[1, 2, 4, 3, 5, 6],
       [3, 4, 7, 5, 2, 9]])

In [18]:
p[:1]

array([[1, 2, 4, 3, 5, 6]])

In [25]:
p[:2,:3]

array([[1, 2, 4],
       [3, 4, 7]])

In [26]:
np.arange(0,5)

array([0, 1, 2, 3, 4])

In [33]:
from random import randint
randint(0,10)

8

In [35]:
np.ones([3,3],dtype=int)

array([[1, 1, 1],
       [1, 1, 1],
       [1, 1, 1]])

In [36]:
np.zeros([3,3],dtype=int)

array([[0, 0, 0],
       [0, 0, 0],
       [0, 0, 0]])

In [38]:
np.linspace(1,10,40)

array([ 1.        ,  1.23076923,  1.46153846,  1.69230769,  1.92307692,
        2.15384615,  2.38461538,  2.61538462,  2.84615385,  3.07692308,
        3.30769231,  3.53846154,  3.76923077,  4.        ,  4.23076923,
        4.46153846,  4.69230769,  4.92307692,  5.15384615,  5.38461538,
        5.61538462,  5.84615385,  6.07692308,  6.30769231,  6.53846154,
        6.76923077,  7.        ,  7.23076923,  7.46153846,  7.69230769,
        7.92307692,  8.15384615,  8.38461538,  8.61538462,  8.84615385,
        9.07692308,  9.30769231,  9.53846154,  9.76923077, 10.        ])

In [39]:
a=np.arange(0,12).reshape(3,4)

In [40]:
a

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [41]:
a1=a.copy()

In [42]:
a1[:2,:2]=500

In [43]:
a1

array([[500, 500,   2,   3],
       [500, 500,   6,   7],
       [  8,   9,  10,  11]])

In [44]:
a

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [49]:
np.identity(5,int)

array([[1, 0, 0, 0, 0],
       [0, 1, 0, 0, 0],
       [0, 0, 1, 0, 0],
       [0, 0, 0, 1, 0],
       [0, 0, 0, 0, 1]])

In [59]:
np.eye(5,6,k=1)

array([[0., 1., 0., 0., 0., 0.],
       [0., 0., 1., 0., 0., 0.],
       [0., 0., 0., 1., 0., 0.],
       [0., 0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 0., 1.]])